workspace:
  base: /srv/app
clone:
  git:
    image: plugins/git:1
    depth: 50
    tags: false

pipeline:
  Deploy:
    image: appleboy/drone-ssh
    host: 159.69.76.172
    port: 2272
    user: root
    secrets: [ ssh_key ]
    script:
      - bash /scripts/script-deploy.sh
    when:
      branch: master
      event: push