kind: pipeline
name: default

workspace:
  base: /srv/app

clone:
  depth: 1

steps:
- name: deploy
  image: appleboy/drone-ssh
  settings:
    secrets: [ host, port, username, ssh_key ]
  script:
    - cd /scripts
    - bash script-deploy.sh
#trigger:
#  branch:
#    - master
#  event:
#    - push
