kind: pipeline
name: default

workspace:
  base: /srv/app

clone:
  depth: 1

steps:
- name: deploy
  image: appleboy/drone-ssh
  host:
    from_secret: host
  port:
    from_secret: port
  username:
    from_secret: username
  key:
    from_secret: ssh_key
  script:
    - bash /scripts/script-deploy.sh
#trigger:
#  branch:
#    - master
#  event:
#    - push
