kind: pipeline
name: default

workspace:
  base: /srv/app

clone:
  depth: 1

steps:
- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 159.69.76.172
    port: 2272
    username: root
    ssh_key:
      from_secret: ssh_key
    script:
      - cd /scripts
      - bash script-deploy.sh
  commands:
    - git config --global --list
  trigger:
    branch:
      - master
    event:
      - push
