kind: pipeline
name: default

clone:
  depth: 1

steps:
  - name: Deploy
    image: appleboy/drone-ssh
    settings:
      host: ianthe.rem.uz
      port: 22
      user: root
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - bash /scripts/script-deploy.sh
    trigger:
      branch:
        - master
      event:
        - push
