kind: pipeline
name: default

workspace:
  base: /srv/app

clone:
  depth: 1

steps:
- name: deploy
  image: appleboy/drone-ssh
  environment:
    USERNAME:
      from_secret: user
    PASSWORD:
      from_secret: ssh_key
  settings:
    host: 
      from_secret: host
    port: 
      from_secret: port
    user:
      from_secret: user
    key:
      from_secret: ssh_key
  script:
    - cd /scripts
    - bash script-deploy.sh

#trigger:
#  branch:
#    - master
#  event:
#    - push
